# Generated by Django 5.1.6 on 2025-03-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_user_type_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('C', 'Codeforces'), ('O', 'OmegaUp'), ('K', 'Kattis'), ('V', 'Vjudge')], max_length=1)),
                ('start_time', models.DateTimeField(auto_now=True, null=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
