# Generated by Django 5.1.6 on 2025-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
