# Generated by Django 5.1.6 on 2025-03-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
