# Generated by Django 5.1.6 on 2025-03-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_codeforces_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codeforces_handle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kattis_handle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='omegaup_handle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
