# Generated by Django 5.1.6 on 2025-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_codeforces_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='platform_id',
            field=models.CharField(default=200, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
