# Generated by Django 5.1.6 on 2025-03-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contest_platform_id_alter_contest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='platform_id',
            field=models.CharField(max_length=10),
        ),
    ]
